# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a07e2accf4554abe060e893ba541b8eed1b48331a1e0090297ca6462fc9f188eb4bd27250f91ffdef3e0baf99d0da08851c2ee1822f18491e581ed528e9a648
  mailchimp_api_key: 24e731c251b6387db8176dce6bda37d6-us9
  mailchimp_cold_email_list_id: 6a53bccbd1
  stripe_secret_key: sk_test_VDvxmre5PQWciFyweKt7Jle2
  stripe_public_key: pk_test_2Kv4bpb1gwISH7a70NmzIdLM
  mailer_default_url: http://localhost:3000
  carrierwave_asset_host: http://localhost:3000
  aws_s3_bucket: healthierchildcare
  s3_access_key: AKIAJDK6B6OKOTZNN67Q
  s3_secret_key: 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
  s3_region: us-east-1
  SURVEYGIZMO_API_TOKEN: 22dcd58622cda2f5c87b65b2abe70420bf75920b7c4b0b2d9d
  SURVEYGIZMO_API_TOKEN_SECRET: A954H8aviF0do  
test:
  secret_key_base: a9b1e483ebf9044503ab9e5c279a18a7a380a81eee12237f4dd0275e2e4a9aacf7741c0b8cc91511a5762661b430f89a8b75e5e78d6a0464b1a44ae7bcb7cff0
  mailchimp_api_key: 12345
  mailchimp_cold_email_list_id: 1
  stripe_secret_key: sk_test_VDvxmre5PQWciFyweKt7Jle2
  stripe_public_key: pk_test_2Kv4bpb1gwISH7a70NmzIdLM
  carrierwave_asset_host: http://localhost:3000
  mailer_default_url: https://healthierchildcarestaging.herokuapp.com
  aws_s3_bucket: healthierchildcare
  s3_access_key: AKIAJDK6B6OKOTZNN67Q
  s3_secret_key: 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
  s3_region: us-east-1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailchimp_api_key: 12345
  mailchimp_cold_email_list_id: 1
  #stripe_secret_key: sk_test_VDvxmre5PQWciFyweKt7Jle2
  #stripe_public_key: pk_test_2Kv4bpb1gwISH7a70NmzIdLM
  stripe_secret_key: sk_live_3fxEpryJv923Saj8BvenTgCQ
  stripe_public_key: pk_live_8q7QpG6vGjOFUwK80Aw9SgZX
  carrierwave_asset_host: http://health-childcare-dev.herokuapp.com/
  mailer_default_url: https://daycarestagingapp.herokuapp.com
  aws_s3_bucket: healthierchildcare
  s3_access_key: AKIAJDK6B6OKOTZNN67Q
  s3_secret_key: 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
  s3_region: us-east-1
  SURVEYGIZMO_API_TOKEN: 22dcd58622cda2f5c87b65b2abe70420bf75920b7c4b0b2d9d
  SURVEYGIZMO_API_TOKEN_SECRET: A954H8aviF0do  
